FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

RUN apt-get update \
 && apt-get install -y build-essential python3-dev

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["vllm", "serve", "nanonets/Nanonets-OCR-s", "--max-model-len", "15000"]